### ISSUE TITLE
Some issues in variable creation

### ISSUE THREAD

**Issue by SUMUKHA-PK** [google/martian#293]
I observed that line [286](https://github.com/google/martian/blob/master/cmd/proxy/main.go#L286) has the variable `err` created as `var err error` and the [next line](https://github.com/google/martian/blob/master/cmd/proxy/main.go#L287) has `x509c, priv, err =..` instead of `x509c, priv, err :=..` 

Since I didn't find a coding style guideline, and the method is not efficient (this is the only place I could find it - haven't gone through the entire repo) this PR has been opened. 

PS : Please do put forth the reasons if I'm wrong or missed something.

**Comment by bramhaghosh** [comment]
In this case, using := is not possible since "x509c" and "priv" are both
already created outside the scope of this statement. Because the other
variables that are being assinged to are already declared, "err" must
already be declared as well - and cannot rely on the shortcut notation ":="
which declares and assigns.

https://golang.org/doc/effective_go.html#redeclaration

**Comment by SUMUKHA-PK** [comment]
If `:=` is used, it just declares the ones that are not declared.

Correct me if I'm wrong, but the above seemed to happen in my practice.
