### ISSUE TITLE
http.ReadRequest would ignore Host header

### ISSUE THREAD

**Issue by Dreamacro** [google/martian#295]
when you request

```
$ curl -H "Host: example.com" localhost
```

the server receives `localhost` instead of `example.com`

root cause: https://golang.org/src/net/http/request.go?s=31358:31409#L942

```go
func ReadRequest(b *bufio.Reader) (*Request, error) {
	return readRequest(b, deleteHostHeader)
}
```

`ReadRequest` delete Host header 🤥

it's a helpful trick for the developer, BTW I know

```
$ curl http://www.example.com --resolve www.example.com:80:127.0.0.1
```

**Comment by admtnnr** [comment]
I may be reading it wrong, but this looks correct per the RFC (https://tools.ietf.org/html/rfc7230#section-5.4):

> When a proxy receives a request with an absolute-form of
   request-target, the proxy MUST ignore the received Host header field
   (if any) and instead replace it with the host information of the
   request-target.  A proxy that forwards such a request MUST generate a
   new Host field-value based on the received request-target rather than
   forward the received Host field-value.

**Comment by Dreamacro** [comment]
@admtnnr yes, I use `curl -x 127.1:8080 -H "Host: example.com" localhost`, and my endpoint server uses the virtual host to distribute the request.

according to `rfc7230#section-5.4`, I have to set `/etc/hosts` or use `curl --resolve` to get the result I want to attain, is that right?

**Comment by admtnnr** [comment]
Yes, I believe your solution of `curl --resolve` is correct way to do this. :)

**Comment by Dreamacro** [comment]
thank you for your patience.
