### ISSUE TITLE
Optionally log request & response bodies?

### ISSUE THREAD

**Issue by bootstraponline** [google/martian#32]
> The body of requests and responses are not logged for performance reasons (chunked encoding).
>
> https://github.com/google/martian/wiki/Modifier-Reference#logging

It'd be nice if one could optionally log request & response bodies. I'm looking for an easy way to dump requests/responses as JSON (ideally [HAR](http://www.softwareishard.com/blog/har-12-spec/)).

**Comment by adamtanner** [comment]
Thanks for the issue! :+1: 

I've updated the docs to reflect some recent changes in `log.Logger` that enable it to log message bodies, optionally dechunking and decompressing them so that they are readable in the log output.

We actually have an implementation of a HAR logger for Martian internally that we held off on open sourcing because it's not entirely to spec. Some places of the spec are vague and there are some fields we just haven't implemented. We can look into prioritizing open sourcing it.

I'd like to understand your use case a bit more though. What problem are you trying to solve with HAR logs? Do you need HAR specifically or would any log formatted as JSON work? I ask because we've talked about doing a more lightweight JSON log format for Martian in the past.

**Comment by bootstraponline** [comment]
I'd be very interested in a HAR logger even if it's not entirely to spec. My use case is Selenium web testing. Typically I use [browsermob-proxy](https://github.com/lightbody/browsermob-proxy) to capture HAR files. This enables testing [a bunch of scenarios](http://elementalselenium.com/tips/tags/browsermob-proxy) that standard selenium is not able to handle.

**Comment by adamtanner** [comment]
Okay, cool. We'll work on cleaning up the HAR implementation.

We built a Verifier API for Martian that was intended to solve these use cases without requiring users to reimplement the verification logic across languages/platforms and enable verifications to be made for requests where loading the entire message body into memory before asserting may not be feasible (video streaming, large file downloads). We have a couple verifiers built in already; here's one for [verifying status codes](https://github.com/google/martian/blob/master/status/status_verifier.go)).

We have a couple open issues for making the API better (#27, #28) and would love feedback if you have any.

**Comment by bootstraponline** [comment]
The issue I have with verifiers is with one of my projects, I'm trying to compare the HAR files across webdriver sessions. To do that I need to persist the request/response information to disk. The approach is similar to [VCR](https://github.com/vcr/vcr).

**Comment by adamtanner** [comment]
Sounds good. Thanks for the insight. :+1:
